### ISSUE TITLE
Second SSD added does not get new files placed onto it

### ISSUE THREAD

**Issue by fredskis** [cjmanca/AllInOne#1]
Hello, I have been using this AIO plug-in for some years with great success. 
Recently I added a 2nd SSD but it seems to be configured as a regular HDD by looking at the red arrow New File Placement target of 0. 

Below is my plug-in config
![AIO config](https://user-images.githubusercontent.com/23066798/175453696-4c7f00ad-58b2-44ed-84c5-452bae14a408.png)

Below is the balancing status. Note 2nd from top drive, S:\ is empty, and has been for the last 4 days or so since this has been configured. 
![DrivePool balancing](https://user-images.githubusercontent.com/23066798/175453679-38903e2b-a7f8-477d-8b56-b42f7b2c8557.png)

I noticed the readme.md included dual SSDs in config so it seems it should be supported?

I have tried changing the SSD back to HDD in the plug-in settings, saving, then changing back to SSD and changing. The server has been through many reboots as well.

**Comment by cjmanca** [comment]
Yes, it's definitely supported and should be working (I use 3 SSDs in my setup with no issues). I'm noticing that it doesn't have a blue arrow either, so it's not being treated as either an SSD or an archive drive.

Two possibilities come to mind:
1. It hasn't done a fresh balancing operation since it was added (was that balancing operation already in progress when you added it? It determines the placement arrows at the start of a balancing pass)
2. You also have the "Stablebit Scanner" plugin, which could be overriding it. Could you check in scanner to see if there are any issues detected with the drive?

**Comment by fredskis** [comment]
Thanks for the prompt response! 

Shouldn't be Scanner as everything is healthy there: 
![Scanner status](https://user-images.githubusercontent.com/23066798/175460464-5ad2a5d4-7131-4e23-93be-8a5900865598.png)


Definitely sounds like option 1. though. I recently added two 18TB drives to the pool and they're still balancing. I likely configured the second SSD after this balancing started, hence those arrows and config hasn't take effect yet. 

I'll keep an eye on it and report back here what happens after the balancing completes, probably will take until after the weekend at this rate.

**Comment by cjmanca** [comment]
You could always stop the balancing and re-start it. It'll recalculate and then restart from where it was, so the only time lost will be the time it takes to re-calculate at the start.

But yes, if you added the SSD after the balancing started then that's almost definitely the reason.

**Comment by fredskis** [comment]
Legend. That did the trick! 
After stopping and restarting balancing, the second SSD was configured and started being used as intended.
